name: Create Git Tag

on:
  pull_request:
    types: [closed]

jobs:
  create_git_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push tag
        if: github.event.pull_request.merged == true && startsWith(github.ref, 'release')
        run: |
          echo "v1-$(TZ=Asia/Tokyo date +%Y%m%d-%H%M%S)" > TAG_NAME
          git tag $(cat TAG_NAME)
          git push origin $(cat TAG_NAME)