name: GitHub Release

on:
  push:
    # branches:
    #   - main

jobs:
  latest_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest release version
        id: latest_release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const query = `query($owner:String!, $name:String!) {
              repository(owner:$owner, name:$name){
                latestRelease {
                  tagName
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo,
            }
            const result = await github.graphql(query, variables)
            return result.repository.latestRelease.tagName
          result-encoding: string

      - name: Increment version
        id: increment_version
        run: |
          current_version="${{steps.latest_release.outputs.result}}"
          echo "Current version: $current_version"
          # Increment the version
          echo "NEW_VERSION=$(echo $current_version | awk -F "." '{print $1 "." $2 "." $3+1}')" >> $GITHUB_OUTPUT
        shell: bash

      # リリースノート作成
      - name: Update Release notes
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           NEW_VERSION: ${{ steps.increment_version.outputs.NEW_VERSION }}
        run: |
          gh release create ${{ env.NEW_VERSION }} --generate-notes -t ${{ env.NEW_VERSION }}