name: Use GitHub API generate_release_notes 

on: push

jobs:
  github:
    runs-on: ubuntu-20.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      # 直前のリリースタグを取得する
      - name: PREVIOUS_TAG_NAME
        run: |
          gh api repos/${REPOSITORY}/tags --jq '.[].name'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
      - name: Push tag
        run: |
          echo "v1-$(TZ=Asia/Tokyo date +%Y%m%d-%H%M%S)" > TAG_NAME
          git tag $(cat TAG_NAME)
          git push origin $(cat TAG_NAME)

      - name: echo env.PREVIOUS_TAG_NAME
        run: echo ${{ env.PREVIOUS_TAG_NAME }}

      - name: GitHub Release # [REST API] GitHub Releases
        run: gh api repos/${REPOSITORY}/releases/generate-notes -F tag_name=$(cat TAG_NAME) -F previous_tag_name=${{ env.PREVIOUS_TAG_NAME }} -F generate_release_notes=true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}