name: GitHub Release

on:
  push:
    # branches:
    #   - main

jobs:
  latest_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest release version
        id: latest_release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const query = `query($owner:String!, $name:String!) {
              repository(owner:$owner, name:$name){
                latestRelease {
                  tagName
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo,
            }
            const result = await github.graphql(query, variables)
            console.log(result.repository)
            console.log(result.repository.latestRelease.tagName)
            return result.repository.latestRelease.tagName
          result-encoding: string
      - name: Increment version
        id: increment_version
        run: |
          current_version="${{steps.latest_release.outputs.result}}"
          echo "Current version: $current_version"
          # Increment the version
          echo "NEW_VERSION=$(echo $current_version | awk -F "." '{print $1 "." $2 "." $3+1}')" >> $GITHUB_OUTPUT
          echo "PREVIOUS_TAG_NAME=$current_version" >> $GITHUB_OUTPUT
        shell: bash

      # リリースノートを自動生成する
      - name: Create GitHub Release
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           NEW_VERSION: ${{ steps.increment_version.outputs.NEW_VERSION }}
           PREVIOUS_TAG_NAME: ${{ steps.increment_version.outputs.PREVIOUS_TAG_NAME }}
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "GENERATED_NOTES<<$EOF" >> $GITHUB_ENV
          $(gh api repos/${REPOSITORY}/releases/generate-notes -F tag_name=${{ env.NEW_VERSION }} -F previous_tag_name=${{ env.PREVIOUS_TAG_NAME }} -F generate_release_notes=true jq .body | sed 's,",,g' | sed "s,',,g") >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV
          echo ${{env.GENERATED_NOTES}}
          echo $GENERATED_NOTES
          echo $GITHUB_ENV

      # リリースノートを更新
      - name: Update Release notes
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           NEW_VERSION: ${{ steps.increment_version.outputs.NEW_VERSION }}
        run: |
          echo ""
          $(gh api repos/${REPOSITORY}/releases -F tag_name=${{ env.NEW_VERSION }} -F body=${{ env.GENERATED_NOTES }})