name: Self Assign Failure

on: push

jobs:
  assign:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - run: gh pr edit $NUMBER --add-assignee $ASSIGNEE
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: 1
          ASSIGNEE: "bot"
      - run: echo "test failure"
