name: Run Kotlin script

on:
  workflow_dispatch:
    inputs:
      awesome-input:
        description: 'Awesome parameter'
        default: 'You'
        required: true

jobs:
  awesome-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Install Kotlin
        run: |
          curl -s https://get.sdkman.io | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install kotlin
          ls -l
          kotlinc -script ./YourScript.main.kts ${{ github.event.inputs.awesome-input }}

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            /opt/hostedtoolcache/Java_Zulu_jdk/17.0.7-7/x64
            # ~/.gradle/wrapper