on:
  pull_request:
  push:
#        types:
#            - opened
#        branches:
#            - 'release/**'

jobs:
  firebase_staging_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
#      - name: Setup Android SDK
#        uses: android-actions/setup-android@v2
      - name: Building
        run: |
          echo "Building..."
          env
